version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Deploying static site to S3..."
      - aws s3 sync ./DevOps25 s3://anjellscloud.com --delete

artifacts:
  files:
    - '**/*'
